baseURL = "https://maupp.ulb.ac.be/"
languageCode = "en-us"
title = "MAUPP"
theme = "maupp"

RelativeURLs=true
CanonifyURLs=true

[params]
    acronym = "MAUPP"
    fullname = "Modeling and forecasting African Urban Population Patterns"

[[menu.main]]
    name = "Project"
    weight = 1
    identifier = "project"
    url = "/page/project/"

[[menu.main]]
    name = "News"
    weight = 2
    identifier = "news"
    url = "/news/"

[[menu.main]]
    name = "Partners"
    weight = 3
    identifier = "partners"
    url = "/partner/"

[[menu.main]]
    name = "Team"
    weight = 4
    identifier = "team"
    url = "/people/"

[[menu.main]]
    name = "Publications"
    weight = 5
    identifier = "publications"
    url = "/page/publications"

[[menu.main]]
    name = "Software"
    weight = 6
    identifier = "software"
    url = "/page/software"

[[menu.main]]
    name = "Data"
    weight = 7
    identifier = "data"
    url = "/page/wp1results"

[[menu.main]]
    name = "Summary"
    weight = 1
    identifier = "summary"
    parent = "project"
    url = "/page/summary"

[[menu.main]]
    name = "Research topic"
    weight = 2
    identifier = "research-topic"
    parent = "project"
    url = "/page/research-topic"

[[menu.main]]
    name = "Objectives"
    weight = 3
    identifier = "objectives"
    parent = "project"
    url = "/page/objectives"

[[menu.main]]
    name = "Methodology"
    weight = 4
    identifier = "methodology"
    parent = "project"
    url = "/page/methodology"
